### ISSUE TITLE
map not load after update android studio

### ISSUE THREAD

**Issue by yasser9372** [NeshanMaps/android-neshan-maps-starter#12]
2019-06-18 02:23:29.148 2764-3273/? E/ActivityTrigger: activityStartTrigger: not whiteListedcom.faradweb.bazara/com.faradweb.bazara.SecondaryActivities.ShowJobsLocationActivity/1
2019-06-18 02:23:29.171 9386-9401/? E/[B+]AppInfoService: null
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:756)
        at com.htc.pitroad.appminer.services.b$a$a.a(SourceFile:122)
        at com.htc.pitroad.appminer.services.AppInfoService.a(SourceFile:852)
        at com.htc.pitroad.appminer.b.a.a(SourceFile:119)
        at com.htc.pitroad.appminer.e.o.a(SourceFile:154)
        at com.htc.pitroad.appminer.services.AppInfoService.a(SourceFile:1747)
        at com.htc.pitroad.appminer.e.p$a$1.invoke(SourceFile:77)
        at java.lang.reflect.Proxy.invoke(Proxy.java:913)
        at $Proxy0.onResult(Unknown Source)
        at android.os.RemoteCallback.sendResult(RemoteCallback.java:73)
        at android.os.RemoteCallback$2.sendResult(RemoteCallback.java:50)
        at android.os.IRemoteCallback$Stub.onTransact(IRemoteCallback.java:56)
        at android.os.Binder.execTransact(Binder.java:682)
2019-06-18 02:23:29.343 24470-24470/com.faradweb.bazara E/neshan-mobile-sdk: MapView Not registered visit https://developers.neshan.org
2019-06-18 02:23:29.355 24470-24470/com.faradweb.bazara E/neshan-mobile-sdk: ClassRegistry: Could not find class: N6neshan10SolidLayerE

بعد از بروزرسانی اندروید استودیو نقشه مانند زمانی که لایسنس ندارد لود میشود. خطای فوق هنگام شروع اکتیویتی رخ میدهد. لطفا راهنمایی بفرمایید 

با تشکر

**Comment by Shahriyar13** [comment]
```
2022-04-26 11:35:45.863 936-936/com.golrang.trademarketing.debug I/carto-mobile-sdk: AndroidUtils::AttachJVM: Attaching JVM from current JNIEnv
2022-04-26 11:35:45.865 936-936/com.golrang.trademarketing.debug W/carto-mobile-sdk: MapView: MapView created before MapView.registerLicense is called
2022-04-26 11:35:45.866 936-936/com.golrang.trademarketing.debug W/carto-mobile-sdk: Bitmap: Warning while loading PNG: iCCP: known incorrect sRGB profile
2022-04-26 11:35:45.867 936-936/com.golrang.trademarketing.debug I/carto-mobile-sdk: BaseMapView: Build: android-|(no branch)|release/v4.2.2-184-gb564d84, time: Aug 31 2020 11:24:17, device type: M2012K11AG, device OS: 12
2022-04-26 11:35:46.003 936-936/com.golrang.trademarketing.debug D/SurfaceView: UPDATE null, mIsCastMode = false
2022-04-26 11:35:46.017 936-1295/com.golrang.trademarketing.debug I/carto-mobile-sdk: BaseMapView::onSurfaceCreated()
2022-04-26 11:35:46.017 936-936/com.golrang.trademarketing.debug D/SurfaceView: UPDATE Surface(name=SurfaceView[com.golrang.trademarketing.debug/com.golrang.trademarketing.ui.main.MainActivity])/@0xd154ed0, mIsProjectionMode = false
2022-04-26 11:35:46.017 936-936/com.golrang.trademarketing.debug D/SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
2022-04-26 11:35:46.017 936-936/com.golrang.trademarketing.debug D/SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
2022-04-26 11:35:46.017 936-936/com.golrang.trademarketing.debug D/SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
2022-04-26 11:35:46.020 936-1295/com.golrang.trademarketing.debug I/carto-mobile-sdk: BaseMapView::onSurfaceChanged(): width: 1080, height: 1866
2022-04-26 11:35:46.022 936-1305/com.golrang.trademarketing.debug I/carto-mobile-sdk: PersistentCacheTileDataSource::loadTile: Loading MapTile [x=10528, y=6450, zoom=14, frameNr=0, id=195165813]
2022-04-26 11:35:46.022 936-1305/com.golrang.trademarketing.debug E/carto-mobile-sdk: MapView Not registered visit https://developers.neshan.org
2022-04-26 11:35:46.022 936-1305/com.golrang.trademarketing.debug I/carto-mobile-sdk: PersistentCacheTileDataSource::loadTile: Failed to load MapTile [x=10528, y=6450, zoom=14, frameNr=0, id=195165813]
2022-04-26 11:35:46.022 936-1305/com.golrang.trademarketing.debug I/carto-mobile-sdk: PersistentCacheTileDataSource::loadTile: Loading MapTile [x=10529, y=6450, zoom=14, frameNr=0, id=195165814]
2022-04-26 11:35:46.023 936-1305/com.golrang.trademarketing.debug E/carto-mobile-sdk: MapView Not registered visit https://developers.neshan.org
2022-04-26 11:35:46.023 936-1305/com.golrang.trademarketing.debug I/carto-mobile-sdk: PersistentCacheTileDataSource::loadTile: Failed to load MapTile [x=10529, y=6450, zoom=14, frameNr=0, id=195165814]
2022-04-26 11:35:46.023 936-1305/com.golrang.trademarketing.debug I/carto-mobile-sdk: PersistentCacheTileDataSource::loadTile: Loading MapTile [x=10528, y=6449, zoom=14, frameNr=0, id=195149429]
2022-04-26 11:35:46.023 936-1305/com.golrang.trademarketing.debug E/carto-mobile-sdk: MapView Not registered visit https://developers.neshan.org
2022-04-26 11:35:46.023 936-1305/com.golrang.trademarketing.debug I/carto-mobile-sdk: PersistentCacheTileDataSource::loadTile: Failed to load MapTile [x=10528, y=6449, zoom=14, frameNr=0, id=195149429]
2022-04-26 11:35:46.023 936-1305/com.golrang.trademarketing.debug I/carto-mobile-sdk: PersistentCacheTileDataSource::loadTile: Loading MapTile [x=10529, y=6449, zoom=14, frameNr=0, id=195149430]
2022-04-26 11:35:46.023 936-1305/com.golrang.trademarketing.debug E/carto-mobile-sdk: MapView Not registered visit https://developers.neshan.org
2022-04-26 11:35:46.023 936-1305/com.golrang.trademarketing.debug I/carto-mobile-sdk: PersistentCacheTileDataSource::loadTile: Failed to load MapTile [x=10529, y=6449, zoom=14, frameNr=0, id=195149430]
2022-04-26 11:35:46.023 936-1305/com.golrang.trademarketing.debug I/carto-mobile-sdk: PersistentCacheTileDataSource::loadTile: Loading MapTile [x=10528, y=6451, zoom=14, frameNr=0, id=195182197]
2022-04-26 11:35:46.023 936-1305/com.golrang.trademarketing.debug E/carto-mobile-sdk: MapView Not registered visit https://developers.neshan.org
2022-04-26 11:35:46.023 936-1305/com.golrang.trademarketing.debug I/carto-mobile-sdk: PersistentCacheTileDataSource::loadTile: Failed to load MapTile [x=10528, y=6451, zoom=14, frameNr=0, id=195182197]
2022-04-26 11:35:46.023 936-1305/com.golrang.trademarketing.debug I/carto-mobile-sdk: PersistentCacheTileDataSource::loadTile: Loading MapTile [x=10529, y=6451, zoom=14, frameNr=0, id=195182198]
2022-04-26 11:35:46.023 936-1305/com.golrang.trademarketing.debug E/carto-mobile-sdk: MapView Not registered visit https://developers.neshan.org
2022-04-26 11:35:46.023 936-1305/com.golrang.trademarketing.debug I/carto-mobile-sdk: PersistentCacheTileDataSource::loadTile: Failed to load MapTile [x=10529, y=6451, zoom=14, frameNr=0, id=195182198]
2022-04-26 11:35:46.023 936-1305/com.golrang.trademarketing.debug I/carto-mobile-sdk: PersistentCacheTileDataSource::loadTile: Loading MapTile [x=10527, y=6450, zoom=14, frameNr=0, id=195165812]
2022-04-26 11:35:46.023 936-1305/com.golrang.trademarketing.debug E/carto-mobile-sdk: MapView Not registered visit https://developers.neshan.org
2022-04-26 11:35:46.023 936-1305/com.golrang.trademarketing.debug I/carto-mobile-sdk: PersistentCacheTileDataSource::loadTile: Failed to load MapTile [x=10527, y=6450, zoom=14, frameNr=0, id=195165812]
2022-04-26 11:35:46.023 936-1305/com.golrang.trademarketing.debug I/carto-mobile-sdk: PersistentCacheTileDataSource::loadTile: Loading MapTile [x=10527, y=6449, zoom=14, frameNr=0, id=195149428]
2022-04-26 11:35:46.023 936-1305/com.golrang.trademarketing.debug E/carto-mobile-sdk: MapView Not registered visit https://developers.neshan.org
2022-04-26 11:35:46.023 936-1305/com.golrang.trademarketing.debug I/carto-mobile-sdk: PersistentCacheTileDataSource::loadTile: Failed to load MapTile [x=10527, y=6449, zoom=14, frameNr=0, id=195149428]
2022-04-26 11:35:46.024 936-1305/com.golrang.trademarketing.debug I/carto-mobile-sdk: PersistentCacheTileDataSource::loadTile: Loading MapTile [x=10527, y=6451, zoom=14, frameNr=0, id=195182196]
2022-04-26 11:35:46.024 936-1305/com.golrang.trademarketing.debug E/carto-mobile-sdk: MapView Not registered visit https://developers.neshan.org
2022-04-26 11:35:46.024 936-1305/com.golrang.trademarketing.debug I/carto-mobile-sdk: PersistentCacheTileDataSource::loadTile: Failed to load MapTile [x=10527, y=6451, zoom=14, frameNr=0, id=195182196]
2022-04-26 11:35:46.027 936-936/com.golrang.trademarketing.debug D/LocationChooserFragment: All location settings are satisfied.
2022-04-26 11:35:46.882 936-936/com.golrang.trademarketing.debug W/carto-mobile-sdk: Bitmap: Warning while loading PNG: iCCP: known incorrect sRGB profile
    
    --------- beginning of crash
2022-04-26 11:35:46.943 936-936/com.golrang.trademarketing.debug A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4 in tid 936 (marketing.debug), pid 936 (marketing.debug)

```
